### PR TITLE
UF-10709: Update dept44 to 6.0.3 and format project

### PR DESCRIPTION
**Pull request by cheezi0747**
## Types of changes

- [ ] Bug fix
- [ ] New feature
- [ ] Removed feature
- [x] Code style update (formatting etc.)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes

## Does this PR introduce a breaking change?
- [ ] Yes (I have stepped the version number accordingly)
- [x] No
      
## Checklist:

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly (if applicable).
- [x] I have added/updated tests to cover my changes (if applicable).

### CODE REVIEW

**Comment by foobar-1337** [comment]
Fix Sonar issues. Do we need to make any adjustments in the formatting-template for this?

**Comment by cheezi0747** [comment]
> Fix Sonar issues. Do we need to make any adjustments in the formatting-template for this?

Yeah so. [These Lines](https://github.com/Sundsvallskommun/dept44/blob/main/dept44-formatting-plugin/src/main/resources/config.xml#L9-L12)
This indent section is replacing spaces in the string literals with `\u0009`. As we are using tabs as the default everywhere the issue has not been made visible. 

In the earlier version we had to hack it like this. But because we are now using the eclipse plugin with our own formatting with tabs as default we dont need it. So if we remove this we can format the code and keep sonar happy. 

I have tried this locally and verified that it works. I do think we should hold off on releasing it as more issues, adjustments and modifications are likely the appear in the upcoming week as we get more hands on this.

**Comment by foobar-1337** [comment]
> > Fix Sonar issues. Do we need to make any adjustments in the formatting-template for this?
> 
> Yeah so. [These Lines](https://github.com/Sundsvallskommun/dept44/blob/main/dept44-formatting-plugin/src/main/resources/config.xml#L9-L12) This indent section is replacing spaces in the string literals with `\u0009`. As we are using tabs as the default everywhere the issue has not been made visible.
> 
> In the earlier version we had to hack it like this. But because we are now using the eclipse plugin with our own formatting with tabs as default we dont need it. So if we remove this we can format the code and keep sonar happy.
> 
> I have tried this locally and verified that it works. I do think we should hold off on releasing it as more issues, adjustments and modifications are likely the appear in the upcoming week as we get more hands on this.

Sure, do we have a story/task for this?

**Comment by cheezi0747** [comment]
> > > Fix Sonar issues. Do we need to make any adjustments in the formatting-template for this?
> > 
> > 
> > Yeah so. [These Lines](https://github.com/Sundsvallskommun/dept44/blob/main/dept44-formatting-plugin/src/main/resources/config.xml#L9-L12) This indent section is replacing spaces in the string literals with `\u0009`. As we are using tabs as the default everywhere the issue has not been made visible.
> > In the earlier version we had to hack it like this. But because we are now using the eclipse plugin with our own formatting with tabs as default we dont need it. So if we remove this we can format the code and keep sonar happy.
> > I have tried this locally and verified that it works. I do think we should hold off on releasing it as more issues, adjustments and modifications are likely the appear in the upcoming week as we get more hands on this.
> 
> Sure, do we have a story/task for this?

We do

https://github.com/Sundsvallskommun/dept44/pull/386

https://jira.sundsvall.se/browse/UF-10724

**Review by AndreSoderlund — APPROVED** [review]

**Pull request merged**
